<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_AN01R4264</name>
   <tag></tag>
   <elementGuidId>2d65eeb5-9400-43e9-8a6d-9da5350a8d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.pure-checkbox > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//angular2-multiselect[@id='selectedVehicles']/div/div[2]/div[3]/ul/span/div/li/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>45052574-839b-44da-b8f4-456606dbff97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AN01R4264</value>
      <webElementGuid>ac459390-c48c-466c-ab0a-0bee5dc1e6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedVehicles&quot;)/div[@class=&quot;cuppa-dropdown&quot;]/div[@class=&quot;dropdown-list&quot;]/div[@class=&quot;list-area&quot;]/ul[@class=&quot;lazyContainer&quot;]/span[1]/div[1]/li[@class=&quot;pure-checkbox&quot;]/label[1]</value>
      <webElementGuid>24743d69-8ddd-4ae6-834a-49d4db874cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//angular2-multiselect[@id='selectedVehicles']/div/div[2]/div[3]/ul/span/div/li/label</value>
      <webElementGuid>6ab612f1-a2b2-47ee-81c6-45728587087c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unselect all'])[1]/following::label[1]</value>
      <webElementGuid>15ca80e4-0e3d-4701-91ae-8949339c66f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/following::label[1]</value>
      <webElementGuid>90510c5d-ae47-47d6-9079-3b4a4a071aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AN01R4291'])[1]/preceding::label[1]</value>
      <webElementGuid>065a05c0-6e51-410a-a925-18b92b43f13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AN01R4256'])[1]/preceding::label[2]</value>
      <webElementGuid>a4f1d87a-427a-41b2-8bee-44b4fa8d7df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AN01R4264']/parent::*</value>
      <webElementGuid>1b4c9c63-a118-465f-9970-2fe4c11e2988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/label</value>
      <webElementGuid>d9c54c41-7981-4c8a-9046-4052c5a0181c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'AN01R4264' or . = 'AN01R4264')]</value>
      <webElementGuid>1857056c-e7bf-4290-ae99-07a09dbbe40f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
