<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_003_VC_Smart_DUAL Profile-IOCL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a796008b-5bba-4aca-a0ca-fa5bfeb51e56</testSuiteGuid>
   <testCaseLink>
      <guid>52425f65-a7f9-482e-9d1f-430930258352</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_018_VC_Smart_Verify Profile login-IOCL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca8e0b46-f804-40c9-85a7-f133860110c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50939fb8-7c93-4518-bbf8-cca11fea9d5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33775378-2cb3-46de-8bf7-633c1f0c49ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>066ef283-1912-4c43-8702-b43d543f97f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC_019_VC_Smart_Home_Element verification-IOCL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b370f9f-6e22-4fd6-a5ae-173ee0a8f55d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b544b04-7d7e-4e60-9a3d-d090cd172e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd017cde-4eff-4ebf-9797-365516ad9a38</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
