<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_001_VC_Smart_Login_Feature</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4feff6a3-844b-486f-87ed-dd0c9c58bb3d</testSuiteGuid>
   <testCaseLink>
      <guid>53f56b01-cb2d-4798-991b-a78e35e2477e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_001_Verify the Login feature with valid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e702f303-27cf-4d56-a7a2-2f99de990c02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_002_Verify the Login feature with invalid credentials</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec0fd2b-ebd6-4df6-a669-ff768554d48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5ad3ced-3cdf-4311-95a7-cd06498c36fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf0910c1-fa0a-43c8-85a3-b612a6632ad4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11e3762e-d13d-4b85-8567-2b439db5e5ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_003_Verify login with multiple user</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>687c61bf-3667-48f5-b801-5b3d86e808a6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Multiple user login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dc72e3a-b0e0-4e3e-96d4-08c326a070f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>687c61bf-3667-48f5-b801-5b3d86e808a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>dd654102-a041-44e6-9146-9d6af800c0da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>687c61bf-3667-48f5-b801-5b3d86e808a6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>e6c8c908-3009-4492-8a2d-d9a777ac7dec</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
