<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deviation report-button_Submit</name>
   <tag></tag>
   <elementGuidId>4dea5d9d-bc58-4064-b24c-fa85f26d7b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitGenericFilterForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitGenericFilterForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d425cd8-f832-4eb5-a31a-8203806a3d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8fa953ca-046b-4e77-a3c1-f118a41dd3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary form-control</value>
      <webElementGuid>a9e5ffa3-1324-4f1c-842d-8393799d00ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitGenericFilterForm</value>
      <webElementGuid>f39c9948-6cd5-4e7c-ba82-1cf0290a99fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>016a73f2-3b31-4fee-bfb0-d993602788a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitGenericFilterForm&quot;)</value>
      <webElementGuid>a6b0f6a2-c121-498e-a82a-4b05c40b35a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitGenericFilterForm']</value>
      <webElementGuid>d86854e8-c42a-4cd3-8502-d1941304c813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='GenericFilterForm']/div[2]/div/span[7]/button[2]</value>
      <webElementGuid>d0c848ce-378a-4884-bdd2-8552bc08ba85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit &amp; Download'])[1]/following::button[1]</value>
      <webElementGuid>bb4eee8c-5999-49a7-8559-c5a7280f42d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::button[2]</value>
      <webElementGuid>6ea37102-bb8c-4c76-9bb9-dabd6e8c0445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click to submit the form'])[1]/preceding::button[1]</value>
      <webElementGuid>4f230ef1-c4f2-4387-9f54-3d8076b05073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::button[1]</value>
      <webElementGuid>ce4bbb57-b339-4591-ad91-c69663b0d3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>83084553-807e-4034-a7a3-85b5caf0c5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/button[2]</value>
      <webElementGuid>4ea003b6-39ac-4590-88df-863c2e280c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'submitGenericFilterForm' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>6cf19e5d-a50a-4c9a-b596-f77453eb454b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
