<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Zoom</name>
   <tag></tag>
   <elementGuidId>82668541-5743-4cce-bb86-0b792a2ed89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tmsi-generic-map-map</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tmsi-generic-map-map']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c02830b5-9116-4c09-9671-7fad39ff8ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tmsi-generic-map-map</value>
      <webElementGuid>96f78abb-9378-4e5c-8a9a-c2593ed58842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-retina leaflet-fade-anim leaflet-grab leaflet-touch-drag</value>
      <webElementGuid>2e9a9dfb-2f4d-4d4a-9028-11c321a7422d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1457abd-b737-4963-ae9c-7bed1d3ece4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>147200 km100 mi+−Leaflet | Google map © Trimble</value>
      <webElementGuid>9a3a0d96-d6e1-47ad-885b-8901a515c8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tmsi-generic-map-map&quot;)</value>
      <webElementGuid>8985cd34-a48f-4d93-8335-c8d5881315f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tmsi-generic-map-map']</value>
      <webElementGuid>b9e753ad-d8d3-40d8-8cee-7a62adcc82f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FMSContainer']/app-mapview/div/div/tmsi-generic-leaflet-map/div/div/div</value>
      <webElementGuid>01f131d4-5a56-48f1-8ef3-d9b5e4d6743b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On trip vehicles:'])[1]/following::div[3]</value>
      <webElementGuid>25645f04-5da1-4e74-a754-59a8dc69130d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untracked vehicles:'])[1]/following::div[3]</value>
      <webElementGuid>952c7ab8-0c8b-448b-aca8-bdd13a55080d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tmsi-generic-leaflet-map/div/div/div</value>
      <webElementGuid>71507e28-1e32-4e68-b2d0-e25d386c456c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tmsi-generic-map-map' and (text() = '147200 km100 mi+−Leaflet | Google map © Trimble' or . = '147200 km100 mi+−Leaflet | Google map © Trimble')]</value>
      <webElementGuid>d4ee42af-b91f-4324-82c7-90e6e09de05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
