<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_009_PROFILE_FMS_SMART_ITL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e2ca4e35-939c-449c-98d6-db612abe1aaa</testSuiteGuid>
   <testCaseLink>
      <guid>fbc2695f-69f8-4d37-9b9e-d4cb1357ca61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/APP_04_PROFILE WISE TC/TC_021_FMS_Smart_ITL_Profile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61481d96-d0d5-4bf0-ba75-628d65c8adba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>506fd5d7-24c9-4b00-808a-84dd3d3161cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b11f004e-0887-46fe-aefe-d53dd7538eb2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
