<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FMSSmart</name>
   <tag></tag>
   <elementGuidId>0de6bf9c-2e4e-47ac-88af-8bfd03e8af70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > div.card > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'FMSSmart')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b74aaecb-8727-4202-8111-2cd7e1ad4425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d6390fd6-cb87-46da-962a-e10b3ea0d73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://fmssmart.tmsitrimble.in/FMSSmartApp/</value>
      <webElementGuid>3ef37774-4eee-4841-9c27-994dfeef7956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FMSSmart</value>
      <webElementGuid>f0dc24b1-2edc-4000-b2e3-02138834d994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;fixed-header w-100&quot;]/nav[@class=&quot;col-12  inline mr-0 pr-0&quot;]/div[@class=&quot;col-6 inline mr-0 pr-2&quot;]/div[@class=&quot;logo left-icons mr-0 pr-0 float-right&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-content&quot;]/table[1]/tr[1]/td[2]/div[@class=&quot;card&quot;]/div[1]/a[1]</value>
      <webElementGuid>5f997c41-fb90-42c5-b8c7-f654b01ee3a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'FMSSmart')]</value>
      <webElementGuid>74e68b09-c50c-4892-888c-a8c87cebd6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VCSmart'])[1]/following::a[1]</value>
      <webElementGuid>74e6f751-731c-4eb7-a228-40b60bd47a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[2]</value>
      <webElementGuid>8d25fa05-ad93-4148-8b69-a947ae30aec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search User'])[1]/preceding::a[1]</value>
      <webElementGuid>8f5bbda5-5341-4949-9fa4-60f46860113e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FMS Smart'])[1]/preceding::a[1]</value>
      <webElementGuid>b04f0ec8-ef6b-4bec-98e0-9d64f373bf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FMSSmart']/parent::*</value>
      <webElementGuid>40996f01-fc71-4a0c-aa38-a4862e8bc918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://fmssmart.tmsitrimble.in/FMSSmartApp/')]</value>
      <webElementGuid>e8a8bfeb-daed-4932-acc5-1c61a02b5f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/a</value>
      <webElementGuid>1fc6b120-37e8-4ec9-b6fb-431e229d0fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://fmssmart.tmsitrimble.in/FMSSmartApp/' and (text() = 'FMSSmart' or . = 'FMSSmart')]</value>
      <webElementGuid>3d59d674-fdec-47fd-a7bc-ae93aa29a8e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
