<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_VCSmart</name>
   <tag></tag>
   <elementGuidId>03ef0ab8-be81-4f89-bb9b-65e511c4fbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td > div.card > div > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'VCSmart')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5be20c12-4e3a-49db-895d-a998ac22861d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>af0aa34e-5ae8-4dd3-8673-58fa80be4e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vcsmart.tmsitrimble.in/VCSmartApp/</value>
      <webElementGuid>262a9056-280a-47e7-a2d6-372fbdd0321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VCSmart</value>
      <webElementGuid>7ae7a036-7b74-4333-9e99-3b471fcb44a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;fixed-header w-100&quot;]/nav[@class=&quot;col-12  inline mr-0 pr-0&quot;]/div[@class=&quot;col-6 inline mr-0 pr-2&quot;]/div[@class=&quot;logo left-icons mr-0 pr-0 float-right&quot;]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-content&quot;]/table[1]/tr[1]/td[1]/div[@class=&quot;card&quot;]/div[1]/a[1]</value>
      <webElementGuid>76e7fcae-7ecf-4a8a-9185-0db52ad8ab18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VCSmart')]</value>
      <webElementGuid>57ed5d4e-11b3-4dda-92fb-4e6c66fc4df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[1]</value>
      <webElementGuid>71e1a514-e343-462d-9608-9e35ba2a2da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FMSSmart'])[1]/preceding::a[1]</value>
      <webElementGuid>f5be9eeb-b4fa-49dc-b22f-921bb9d9d1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search User'])[1]/preceding::a[2]</value>
      <webElementGuid>77f5123b-15b0-4abc-8d08-97ffcd6a83a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VCSmart']/parent::*</value>
      <webElementGuid>a3a35229-b228-4a98-ae21-e65934d09289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vcsmart.tmsitrimble.in/VCSmartApp/')]</value>
      <webElementGuid>61941bd1-36f3-4564-8d0b-23c75b3358a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/a</value>
      <webElementGuid>12ac4448-76a0-4d99-9c42-f41b218a4c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://vcsmart.tmsitrimble.in/VCSmartApp/' and (text() = 'VCSmart' or . = 'VCSmart')]</value>
      <webElementGuid>f71ae1bf-8347-4701-9c37-ad85d5e20228</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
