<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Userprofile</name>
   <tag></tag>
   <elementGuidId>5473a39c-fd36-4c05-83c3-32e31afbd659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-user-circle-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>44b63420-bef4-453c-8302-8c8dc22230d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user-circle-o</value>
      <webElementGuid>22241bda-d982-4e60-93ce-b7c7620fd134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;fixed-header w-100&quot;]/nav[@class=&quot;col-12  inline mr-0 pr-0&quot;]/div[@class=&quot;col-6 inline mr-0 pr-2&quot;]/div[@class=&quot;logo left-icons mr-0 pr-0 float-right&quot;]/div[@class=&quot;dropdown&quot;]/i[@class=&quot;fa fa-user-circle-o&quot;]</value>
      <webElementGuid>426812dc-a9d7-47c8-9673-3e8d58a69325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>7e1916bf-761e-4d68-ab30-d210a2677a0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
