<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CLose Grid Button</name>
   <tag></tag>
   <elementGuidId>474ef263-3ba6-4156-b9fc-deabeef64d82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeModalDirective3 > span.fa.fa-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeModalDirective3']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>405bd869-5122-40f7-ad48-199d0f1e9d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>99102256-86bc-4e39-bcd0-cf9096f26257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-close</value>
      <webElementGuid>8009d46f-1a42-45b6-997b-1244eeb6b439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeModalDirective3&quot;)/span[@class=&quot;fa fa-close&quot;]</value>
      <webElementGuid>854ab16b-5865-4906-834c-eb3b9495d50a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='closeModalDirective3']/span</value>
      <webElementGuid>f96619bd-5a76-4072-b383-49242df21cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//modal-container/div/div/div/button/span</value>
      <webElementGuid>6e93a2d1-7df4-47b2-a642-132dce0ad9eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
