<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_On Trip Safety Violation (830 Vehicles)</name>
   <tag></tag>
   <elementGuidId>82371392-4b51-4fe6-b4b8-71bcbc42050f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SD_3']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab668638-7ad6-4e12-a17a-b6cdd3061f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-heading</value>
      <webElementGuid>aa2c1745-56e9-4e46-ad35-a52fc028ca66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Trip Safety Violation (830 Vehicles)</value>
      <webElementGuid>5b206da4-ff06-4dfb-ab3a-74eedd5cfe80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SD_3&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]</value>
      <webElementGuid>2a4d975e-478f-4499-915a-eb03e0455b29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SD_3']/div/div</value>
      <webElementGuid>15fd94f2-0963-44ac-8efa-db10d0dfb622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TERMINAL'])[1]/following::div[3]</value>
      <webElementGuid>fac4826f-7da0-49b8-8726-70d4e09b9423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOTIHARI'])[1]/following::div[3]</value>
      <webElementGuid>eb57f522-7461-41f8-bfcd-39755ad86aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div</value>
      <webElementGuid>f6f54740-219f-42c6-a2e4-63a7b0f1e636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'On Trip Safety Violation (830 Vehicles)' or . = 'On Trip Safety Violation (830 Vehicles)')]</value>
      <webElementGuid>945c5dab-5fac-4be2-ad00-49314b906357</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
