<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5 Star</name>
   <tag></tag>
   <elementGuidId>93edd5d5-1433-4d0e-ad9f-9d61ee3328b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='star4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7becb3b5-24c5-4cc7-bd58-9fa1000b8939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-boxes</value>
      <webElementGuid>5fff6997-f91d-4833-b6bc-baf10a13f147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star4</value>
      <webElementGuid>a1108038-dcd8-40a9-a15b-32dce7450345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 5 </value>
      <webElementGuid>137f5fb1-d644-4542-94ee-4de09258c480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star4&quot;)</value>
      <webElementGuid>cd0e9050-7fb0-44fa-a13d-d1d43f9f3278</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='star4']</value>
      <webElementGuid>fc4e9d56-de21-4def-9817-e454cf708d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedback-modal']/div[2]/div[2]/div[5]</value>
      <webElementGuid>2e5b63e6-0911-4d87-b1fc-c6d5cc8bea26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate our product'])[1]/following::div[6]</value>
      <webElementGuid>637dc264-4685-4be3-afba-4156f922ae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::div[9]</value>
      <webElementGuid>322e0aed-37a1-4bd1-9551-d9b23b48184e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Star'])[1]/preceding::div[2]</value>
      <webElementGuid>12c5f5af-b4ba-4f9a-9fee-4faafdc3c1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Feedback'])[1]/preceding::div[9]</value>
      <webElementGuid>3aad8ce5-fbf5-4a8d-a742-42ffed03e5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]</value>
      <webElementGuid>ab75d89e-2eee-4cfa-a43e-6f83e3390432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'star4' and (text() = ' 5 ' or . = ' 5 ')]</value>
      <webElementGuid>cb27128e-601d-4a2c-bb1d-d830828c4f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
