<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Others</name>
   <tag></tag>
   <elementGuidId>09684562-de7e-46b8-9ab9-19c4eeb07787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bug2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='bug2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa180339-be90-4c10-aaaa-578d45b45cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control center-align</value>
      <webElementGuid>6927d0d8-bd91-4886-bec9-1964430277d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bug2</value>
      <webElementGuid>21e7c221-8521-47da-a288-010045b01f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Others </value>
      <webElementGuid>23e23dbf-07f3-4dc4-b53a-62a7f45ed5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bug2&quot;)</value>
      <webElementGuid>1821a0b3-38b0-4079-bfdd-a5239daedad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='bug2']</value>
      <webElementGuid>fb073334-a4ac-40ce-8efc-9c455fafb45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='myDIV']/button)[3]</value>
      <webElementGuid>904625ba-6db8-4068-876a-407e1a6dbdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Feature'])[1]/following::button[1]</value>
      <webElementGuid>f86452e7-426e-443c-90b7-509f7258b268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue'])[1]/following::button[2]</value>
      <webElementGuid>dc61ba3f-b41e-480c-b3c3-ac508858a2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide more details'])[1]/preceding::button[1]</value>
      <webElementGuid>54505473-22a7-4d8d-b4e2-d67a87c9ec3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(character limit : 2000)'])[1]/preceding::button[1]</value>
      <webElementGuid>d53110b6-fdf3-4071-bfc5-69d20dbb7db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Others']/parent::*</value>
      <webElementGuid>1f76d097-7f8a-4f48-a403-99fed3737840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/button</value>
      <webElementGuid>ef7b1e88-4a58-4162-896a-9f52cbe6f76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'bug2' and (text() = ' Others ' or . = ' Others ')]</value>
      <webElementGuid>1686adad-59eb-4267-b1d8-4b3babee8414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
