<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload</name>
   <tag></tag>
   <elementGuidId>f44a2b5d-7fd2-4d0f-a116-eab103a15543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.custom-file-upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedback-modal']/div[2]/form/div[5]/div[2]/label/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6ab28bce-6abc-4cc4-ae57-7788fd6f8d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-upload</value>
      <webElementGuid>f0660fc1-7fcd-4db8-861e-468646da7b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>file-upload</value>
      <webElementGuid>8e9e9872-f3b8-48f7-9000-26f2807b6252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Upload </value>
      <webElementGuid>1d8094bb-4202-42fc-9d17-6dc05896c9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedback-modal&quot;)/div[2]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;d-flex mb-2 justify-content-between align-items-center&quot;]/div[@class=&quot;tooltip&quot;]/label[@class=&quot;custom-file-upload&quot;]</value>
      <webElementGuid>4909d002-ecce-4fb1-9eab-7de0f634554d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedback-modal']/div[2]/form/div[5]/div[2]/label</value>
      <webElementGuid>70dbcabe-2327-4910-a181-24d09a52911a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File upto 2MB'])[1]/following::label[1]</value>
      <webElementGuid>2c89bfce-4a0a-4b39-bd3a-94254c55f421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(character limit : 2000)'])[1]/following::label[1]</value>
      <webElementGuid>5da0558a-1f0a-4488-9c91-5ce276682742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Feedback'])[1]/preceding::label[1]</value>
      <webElementGuid>1fa71b5b-171e-4116-9a27-174822f3a017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload']/parent::*</value>
      <webElementGuid>137391e5-aa45-4e66-9c48-803b543001af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>a1f97bfa-06d0-45af-8a9a-0ab48a87f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Upload ' or . = ' Upload ')]</value>
      <webElementGuid>24860feb-f75b-4fba-9bec-7398b97cc27d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
